apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: three-tier
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None # This is a headless service